services:
  bot:
    build: .
    ports:
      - "8180:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}},job=dockerlogs"
  db:
    image: postgres
    volumes:
      - /mnt/data/postgres2:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: Choking2-Yapping-Reach
      PGDATA: /var/lib/postgresql/data/pgdata
      PUID: 0
      PGID: 0
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
  adminer:
    image: adminer
    restart: always
    ports:
      - 8069:8080